  name: adl4cv
  channels:
    - pytorch
    - conda-forge
  dependencies:
    - python=3.6
    - numpy
    - pytorch=1.2.0
    - cpuonly
    - torchvision
    - jupyter
    - tensorboard
    - matplotlib
    - plyfile
    - easydict
    - msgpack-numpy
    - h5py
    - scikit-image
    - tqdm
    - lmdb
    - pip
    - pip:
        - minieigen
        - tensorboardx
        - 'trimesh>=2.35.39,<2.35.40'
        - 'networkx>=2.2,<2.3'
        - hydra-core
        - pytorch-lightning
        - ../Pointnet2_PyTorch/pointnet2_ops_lib/.

